.\" Manpage for getjobinfo
.\" Please open an issue on GitHub or fork and push changes to the
.\" repository to correct errors or typos.

.SH NAME

.SH SYNOPSIS

.SH DESCRIPTION

.SH OPTIONS

.SH FILES

.SH EXAMPLES

.SH SEE ALSO

.SH BUGS

.SH AUTHOR
Jason C. Nucciarone (jcn23@psu.edu, jason.nucciarone@gmail.com)

.SH COPYRIGHT
Copyright 2021 Jason C. Nucciarone. All rights reserved at https://www.gnu.org/licenses/gpl-3.0.en.html.
